version: '3.9'

services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: ecommerce-client
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3001
    depends_on:
      - json-server
    networks:
      - ecommerce-net

  json-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: ecommerce-json-server
    ports:
      - "3001:3001"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge